platform :ios, "7.0"

# https://github.com/AFNetworking/AFNetworking.git
pod 'AFNetworking', '~> 3.1.0'

# https://github.com/CoderMJLee/MJRefresh.git
pod 'MJRefresh', '~> 3.1.0'


# https://github.com/matej/MBProgressHUD.git
pod 'MBProgressHUD', '~> 0.9.2'

#  图片请求 https://github.com/rs/SDWebImage.git
pod 'SDWebImage', '~> 3.7.5'

# 状态栏  https://github.com/MoZhouqi/KMNavigationBarTransition/blob/master/README_CN.md
pod 'KMNavigationBarTransition', '~> 0.0.7'

#键盘管理 https://github.com/hackiftekhar/IQKeyboardManager
pod 'IQKeyboardManager', '~> 3.3.7'

#圆角控件  https://github.com/raozhizhen/JMRoundedCorner.git
pod 'JMRoundedCorner', '~> 1.2.1'